-- 1. 고객 정보 및 포인트 저장을 위한 테이블
CREATE TABLE customers (
  phone_number TEXT PRIMARY KEY, -- 전화번호를 기본 키로 사용
  points NUMERIC DEFAULT 0,     -- 포인트 (소수점 가능)
  created_at TIMESTAMPTZ DEFAULT NOW() -- 생성 시각
);

-- 2. 개별 주문 정보를 저장하기 위한 테이블
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- 고유한 주문 ID
  created_at TIMESTAMPTZ DEFAULT NOW(),           -- 주문 시각
  total_amount NUMERIC NOT NULL,                 -- 총 주문 금액
  customer_phone TEXT REFERENCES customers(phone_number) -- 고객 테이블과 연결 (선택적)
);

-- 3. 한 주문에 포함된 여러 메뉴를 저장하기 위한 테이블
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 각 항목의 고유 ID
  order_id UUID NOT NULL REFERENCES orders(id),        -- 주문 테이블과 연결
  product_name TEXT NOT NULL,                          -- 상품명
  quantity INTEGER NOT NULL,                           -- 수량
  price_per_item NUMERIC NOT NULL                      -- 개당 가격
);